package org.broadinstitute.ddp.android.pepper.internal.common

internal object Constants {

    const val WORKFLOW_STATE_TASK = "ACTIVITY"
    const val WORKFLOW_STATE_RETURN_USER = "RETURN_USER"
    const val WORKFLOW_STATE_START = "START"

    const val USER_SEX_MALE = "MALE"
    const val USER_SEX_FEMALE = "FEMALE"
    const val USER_SEX_INTER_SEX = "INTERSEX"
    const val USER_SEX_PREFER_NOT_TO_ANSWER = "PREFER_NOT_TO_ANSWER"

    const val STEP_TYPE_COMPONENT = "COMPONENT"
    const val STEP_TYPE_CONDITIONAL = "CONDITIONAL"
    const val STEP_TYPE_GROUP = "GROUP"
    const val STEP_TYPE_QUESTION = "QUESTION"
    const val STEP_TYPE_CONTENT = "CONTENT"

    const val COMPONENT_TYPE_MAILING_ADDRESS = "MAILING_ADDRESS"
    const val COMPONENT_TYPE_PHYSICIAN = "PHYSICIAN"
    const val COMPONENT_TYPE_INSTITUTION = "INSTITUTION"

    const val QUESTION_TYPE_PICK_LIST = "PICKLIST"
    const val QUESTION_TYPE_TEXT = "TEXT"
    const val QUESTION_TYPE_BOOLEAN = "BOOLEAN"
    const val QUESTION_TYPE_DATE = "DATE"
    const val QUESTION_TYPE_COMPOSITE = "COMPOSITE"
    const val QUESTION_TYPE_AGREEMENT = "AGREEMENT"

    const val FORM_TYPE_CONSENT = "CONSENT"
    const val FORM_TYPE_GENERAL = "GENERAL"
    const val FORM_TYPE_PREQUALIFIER = "PREQUALIFIER"

    const val LIST_STYLE_HINT_NUMBER = "NUMBER"
    const val LIST_STYLE_HINT_BULLET = "BULLET"
    const val LIST_STYLE_HINT_NONE = "NONE"

    const val TASK_TYPE_FORMS = "FORMS"

    const val TASK_STATUS_CREATED = "CREATED"
    const val TASK_STATUS_IN_PROGRESS = "IN_PROGRESS"
    const val TASK_STATUS_COMPLETE = "COMPLETE"

    const val NEXT_TASK = "ACTIVITY"
    const val NEXT_DASHBOARD = "DASHBOARD"
    const val NEXT_DONE = "DONE"
    const val NEXT_MAILING_LIST = "MAILING_LIST"
    const val NEXT_THANK_YOU = "THANK_YOU"
    const val NEXT_INTERNATIONAL_PATIENTS = "INTERNATIONAL_PATIENTS"
    const val NEXT_UNKNOWN = "UNKNOWN"

    const val PICKLIST_RENDER_MODE_LIST = "LIST"
    const val PICKLIST_RENDER_MODE_CHECKBOX_LIST = "CHECKBOX_LIST"
    const val PICKLIST_RENDER_MODE_DROPDOWN = "DROPDOWN"

    const val DATE_RENDER_MODE_TEXT = "TEXT"
    const val DATE_RENDER_MODE_PICKLIST = "PICKLIST"

    const val TEXT_INPUT_TYPE_TEXT = "TEXT"
    const val TEXT_INPUT_TYPE_ESSAY = "ESSAY"
    const val TEXT_INPUT_TYPE_SIGNATURE = "SIGNATURE"

    const val INSTITUTION_TYPE_INSTITUTION = "INSTITUTION"
    const val INSTITUTION_TYPE_INITIAL_BIOPSY = "INITIAL_BIOPSY"
    const val INSTITUTION_TYPE_PHYSICIAN = "PHYSICIAN"

    const val INSTITUTION_TYPE_PATH_INSTITUTION = "institution"
    const val INSTITUTION_TYPE_PATH_INITIAL_BIOPSY = "initial-biopsy"
    const val INSTITUTION_TYPE_PATH_PHYSICIAN = "physician"

    const val TRACKING_STATUS_INELIGIBLE = "INELIGIBLE"
    const val TRACKING_STATUS_PENDING = "PENDING"
    const val TRACKING_STATUS_SENT = "SENT"
    const val TRACKING_STATUS_RECEIVED = "RECEIVED"

    const val VALIDATION_DATE_RANGE = "DATE_RANGE"
    const val VALIDATION_REQUIRED = "REQUIRED"
    const val VALIDATION_COMPLETE = "COMPLETE"
    const val VALIDATION_AGE_RANGE = "AGE_RANGE"

    const val DATE_QUESTION_FIELD_YEAR = "YEAR"
    const val DATE_QUESTION_FIELD_MONTH = "MONTH"
    const val DATE_QUESTION_FIELD_DAY = "DAY"

    const val SUGGESTION_TYPE_NONE = "NONE"
    const val SUGGESTION_TYPE_DRUG = "DRUG"
    const val SUGGESTION_TYPE_INCLUDED = "INCLUDED"

    const val PRESENTATION_DEFAULT = "DEFAULT"
    const val PRESENTATION_MERGE = "MERGE"
}